const de = {
    "welcome_to": "Willkommen bei 👋",
    "app_name": "Billka AI",
    "app_description": "Aufteilung & Analyse der Einnahmen",
    "please_login": "Bitte melde dich an, um fortzufahren",
    "enter_credentials": "Geben Sie Ihre Anmeldeinformationen ein",
    "login_email": "E-Mail",
    "login_password": "Passwort",
    "validation_error_password": "Das Passwort muss mindestens 6 Zeichen lang sein",
    "login_via_email": "Login via E-Mail",
    "login_with_google": "Mit Google anmelden",
    "or": "oder",
    "login": "Anmeldung",
    "sign_up": "Registrieren",
    "forgot_password": "Passwort vergessen?",
    "reset_password": "Passwort zurücksetzen",
    "forgot_password_instructions": "Geben Sie Ihre E-Mail-Adresse ein, und wir senden Ihnen einen Code zum Zurücksetzen Ihres Passworts.",
    "send_reset_code": "Code senden",
    "verify_code": "Code überprüfen",
    "verify_code_instructions": "Geben Sie den 6-stelligen Code ein, den wir an Ihre E-Mail-Adresse gesendet haben.",
    "verification_code": "6-stelliger Code",
    "new_password": "Neues Passwort",
    "new_password_instructions": "Erstellen Sie ein neues Passwort für Ihr Konto.",
    "confirm_password": "Passwort bestätigen",
    "passwords_dont_match": "Passwörter stimmen nicht überein",
    "update_password": "Passwort aktualisieren",
    "logout": "Abmelden",
    "welcome": "Willkommen",
    "hello": "Hallo!🌙",
    "good_morning": "Guten Morgen!☀️",
    "good_afternoon": "Guten Tag!👋",
    "good_evening": "Guten Abend!🌃",
    "greeting": "Hoffentlich haben Sie einen wunderbaren Tag!",
    "upload_bill_modal_header": "Rechnung hochladen",
    "upload_bill_modal_description": "Wählen Sie ein Foto aus Ihrer Galerie oder nehmen Sie ein neues Foto auf.",
    "upload_bill_modal_take_photo": "📸 Ein Foto machen",
    "upload_bill_modal_gallery": "🖼️ Wählen Sie aus der Galerie",
    "upload_bill": "Rechnung hochladen",
    "recognize_fast": "⚡️ Schnell",
    "recognize_quality": "🔥 Hochwertig",
    "manage_receipts": "Rechnungen verwalten",
    "list_of_friends": "Liste der Freunde",
    "cancel": "Abbrechen",
    "recognizing_in_progress_title": "Machen Sie eine kleine Pause...",
    "recognizing_in_progress_msg": "Wir erkennen die Artikel auf Ihrer Rechnung.\nEs wird nicht lange dauern",
    "error_header": "Oops! Etwas ist schief gelaufen",
    "error_large_photo_header": "Das Bild ist zu groß",
    "error_large_photo_msg": "Bitte machen Sie ein neues Foto oder laden Sie eine Datei mit einer Größe von weniger als 10 MB hoch",
    "error_retake_photo_msg": "Wir konnten die Rechnung auf Ihrem Foto nicht erkennen 😥\nBitte machen Sie das Foto erneut",
    "error_retry_fetch_msg": "Entschuldigung, es ist ein Ladefehler aufgetreten 😥\nBitte versuchen Sie es erneut",
    "error_go_home_action": "Nach Hause gehen",
    "error_retake_photo_action_camera": "Foto wiederholen",
    "error_retake_photo_action_gallery": "Foto aus der Galerie",
    "error_retry_action": "Wiederhol",
    "error_creating_friend_header": "Fehler beim Erstellen eines Freundes",
    "error_creating_friend_description": "Es ist ein unerwarteter Fehler aufgetreten. Bitte versuchen Sie es erneut",
    "try_again": "Erneut versuchen",
    "gallery": "Galerie",
    "take-photo": "Ein Foto machen",
    "flash": "Blitzlicht",
    "permission-denied": "Bitte um Erlaubnis für die Kamera",
    "grant-permission": "Erlaubnis erteilen",
    "camera_permission_error": "Kameraberechtigung verweigert",
    "camera_permission_error_description": "Bitte erteilen Sie die Berechtigung, um ein Foto aufzunehmen",
    "bill_ready_to_split_header": "Nur noch ein Schritt...",
    "bill_ready_to_split_body": "Wir müssen die Artikel auf Ihrer Rechnung erkennen.\nBitte wählen Sie unten die Art und Weise:",
    "view_receipt_details": "Details zur Quittung anzeigen",
    "choosing_flow_header": "Ihre Rechnung wird anerkannt!",
    "choosing_flow_description": `Möchten Sie es unter Ihren Freunden aufteilen
 oder nur die Ergebnisse ansehen?`,
    "view_without_splitting": "Ansicht ohne Aufteilung",
    "split_the_bill": "Rechnung aufteilen",
    "splitting_view_next_button": "Splitting-Ergebnisse anzeigen",
    "next": "Weiter",
    "discount": "rabatt",
    "tip": "trinkgeld",
    "edit_bill_action": "Rechnung bearbeiten",
    "bill_items": "Rechnungsposten",
    "no_items_splitting_title": "Keine Artikel übrig",
    "no_items_splitting_description": "Ihre Rechnung enthält keine Posten.\nDrücken Sie die Taste \"+\", um einen Posten manuell hinzuzufügen.",
    "unselected_items": "Nicht ausgewählte Posten",
    "itemDescription": "%{quantity}%{optionalOfQuantity} × %{itemPrice}",
    "optionalOfQuantity": " (von %{itemQuantity})",
    "cancel_changes": "Änderungen abbrechen",
    "splitting_not_saving": "Der Fortschritt der Aufteilung wird nicht gespeichert",
    "yes": "Ja",
    "no": "Nein",
    "add_friend_tab_new_friend": "Neuer Freund",
    "add_friend_tab_all_friends": "Alle Freunde",
    "enter_name": "Geben Sie den Namen ein",
    "add_friend_input_name_placeholder": "Geben Sie den Namen ein",
    "add_email": "E-Mail hinzufügen (optional)",
    "add_favorite": "Zu Favoriten hinzufügen",
    "add_friend_input_email_placeholder": "z.B. john.doe@gmail.com",
    "add_friend_btn": "Bestätige %{splitterName}",
    "add_friends_modal_title": "Freunde hinzufügen",
    "add_friend_modal_title": "Einen Freund hinzufügen",
    "add_friends_modal_new_splitter_description": "Ein Freund wird nur gespeichert, wenn die Rechnung gespeichert wird.",
    "name": "Name",
    "email": "E-Mail (optional)",
    "update_friend_modal_title": "Freund aktualisieren",
    "edit_name": "Der Name darf nicht leer sein und muss eindeutig sein",
    "edit_email_validation": "E-Mail muss im Format user@example.com vorliegen, mit einem '@' und einer gültigen Domain",
    "friend_name_invalid": "Ein Freund mit diesem Namen existiert bereits",
    "friend_email_invalid": "Geben Sie eine gültige E-Mail ein",
    "previous_friends_favorite_group": "Favoriten",
    "previous_friends_nonfavorite_group": "Andere",
    "add_friend_discard_changes_title": "Änderungen verwerfen?",
    "add_friend_discard_changes_description": "Alle Änderungen gehen dann verloren. Möchten Sie fortfahren?",
    "add_friend_discard_changes_no": "Nein, bleiben",
    "add_friend_discard_changes_yes": "Ja, Änderungen verwerfen",
    "change_friend_modal_title": "Freund ändern",
    "change_friend_btn": "Freund ändern",
    "delete_friend_btn": "Freund löschen",
    "delete_friend_header": "Sind Sie sicher, dass Sie diesen Freund löschen wollen?",
    "delete_friend_description": "Die Artikel dieser Person werden ebenfalls freigegeben. Diesen Freund löschen?",
    "me": "Mich",
    "my": "mein",
    "item": "Artikel",
    "items": "Artikel",
    "add_to_bill": "Füge %{quantity} %{itemWord} zur Rechnung von %{splitterName} hinzu (%{price})",
    "add_to_my_bill": "Füge meiner Rechnung %{quantity} %{itemWord} hinzu (%{price})",
    "cancel_splitting_question": "Splitting abbrechen?",
    "cancel_splitting": "Splitting abbrechen",
    "continue_splitting": "Weiter splitten",
    "finish": "Fertig",
    "finish_splitting": "Aufteilung beenden",
    "finish_splitting_title": "Ergebnis aufteilen",
    "finish_splitting_no_items_title": "Es wurden keine Posten aufgeteilt",
    "finish_splitting_no_items_description": "Um die Aufteilungsergebnisse anzuzeigen, weisen Sie einem oder mehreren Freunden auf dem Aufteilungsbildschirm Posten aus Ihrer Rechnung zu.",
    "finish_splitting_back": "Zurück zum Aufteilen",
    "finish_splitting_modal_title": "Ergebnis speichern?",
    "finish_splitting_modal_save_with_splitting": "Mit Aufteilung speichern",
    "finish_splitting_modal_save_without_splitting": "Ohne Aufteilung speichern",
    "finish_splitting_modal_dont_save": "Nicht speichern",
    "friend_no_name": "Ihre Artikel %{emoji}",
    "friend_with_name": "Die Artikel von %{name} %{emoji}",
    "share_button": "Teilen",
    "share_message_title": "Hallo! Hier ist dein Anteil an der Rechnung von %{storeName} am %{date}.",
    "share_all_message_title": "Hallo! Hier ist ein Anteil der Rechnung von %{storeName} am %{date}.",
    "share_message_title_no_date": "Hallo! Hier ist dein Anteil an der Rechnung von %{storeName}.",
    "share_all_message_title_no_date": "Hallo! Hier ist dein Anteil an der Rechnung von %{storeName}.",
    "share_message_person": "== %{name} %{emoji} - %{totalPrice} ==\n%{items}",
    "share_message_splitting": "%{name} - %{totalPrice}",
    "share_message_total": "Ihr Gesamtbetrag beträgt %{totalPrice} 🤗",
    "share_all_message_total": "Der Gesamtbetrag beträgt %{totalPrice} 🤗",
    "your_items": "Ihre Artikel",
    "splitting_header": "Artikel von %{splitterName} %{emoji}",
    "ok": "OK",
    "can_not_change_friend": "Sie können nicht ändern Freund",
    "confirm_before_change_friend": "Bestätigen Sie Artikel, bevor Sie den Freund wechseln",
    "divide_item": "Artikel teilen",
    "edit_item": "Artikel bearbeiten",
    "delete_item": "Artikel löschen",
    "edit_item_modal_header": "Artikel bearbeiten",
    "edit_item_modal_description": "Bearbeiten Sie die Informationen zu Ihrem Artikel",
    "edit_item_modal_save": "Speichern",
    "edit_item_modal_cancel": "Abbrechen",
    "edit_item_name_field": "Artikelname",
    "edit_item_name_field_placeholder": "Geben Sie den Artikelnamen ein",
    "edit_item_name_validation": "Bitte geben Sie den Namen des Artikels ein",
    "edit_item_price_field": "Preis",
    "edit_item_price_validation": "Der Preis sollte digital sein",
    "edit_item_currency_validation": "Nicht gültiger Währungscode",
    "edit_item_discount_field": "Rabatt",
    "edit_item_discount_validation": "Der Rabatt muss 0 oder größer sein",
    "edit_item_quantity_field": "Menge",
    "edit_item_quantity_validation_zero": "Die Menge sollte größer als 0 sein",
    "edit_item_quantity_validation_splitted": "Die Menge sollte größer als die bereits aufgeteilte Menge sein",
    "edit_item_total_price_field": "Gesamtpreis (automatisch berechnet)",
    "edit_item_total_price_with_discount": "Gesamtpreis mit %",
    "edit_item_view_bill_action": "Rechnung anzeigen",
    "edit_item_about_editing_action": "Über die Bearbeitung von Splits",
    "edit_item_about_editing_modal_description": `
Da Sie diesen Artikel bereits gesplittet haben, ändern Sie jetzt den ursprünglichen Artikel und nicht das ausgewählte Splitting.
                            
Wenn Sie den Preis ändern, werden wir Ihre Aufteilung neu berechnen. Leider können Sie den Betrag nur um den Wert reduzieren, der für diesen Artikel noch übrig ist.
                            
Um ihn noch weiter zu reduzieren, sollten Sie die Aufteilung entfernen.`.trim(),
    "edit_item_about_editing_modal_ok": "Verstanden",
    "edit_bill_name_field": "Name des Geschäfts",
    "edit_bill_name_field_placeholder": "Geben Sie den Namen des Geschäfts ein",
    "edit_bill_name_validation": "Bitte geben Sie den Namen des Geschäfts ein",
    "reset_all_changes_to_the_item": "Alle Änderungen an dem Element %{name} zurücksetzen",
    "reset_all_changes_to_the_item_description": "%{name} wird durch den Originalnamen ersetzt. Möchten Sie fortfahren?",
    "discard_changes_modal_header": "Änderungen verwerfen?",
    "discard_item_changes_modal_description": "Alle Änderungen am Artikel werden nicht gespeichert. Möchten Sie fortfahren?",
    "discard_receipt_changes_modal_description": "Alle an der Rechnung vorgenommenen Änderungen werden nicht gespeichert, möchten Sie fortfahren?",
    "discard_bug_report_modal_description": "Alle vorbereiteten Daten für den Fehlerbericht gehen verloren. Möchten Sie fortfahren?",
    "discard_changes_modal_no": "Nein, bleiben",
    "discard_changes_modal_yes": "Ja, Änderungen verwerfen",
    "save": "Speichern",
    "edit_bill_general_info": "Allgemeine Informationen zur gescannten Rechnung. Wenn einige Informationen nicht korrekt sind, bitte die Parameter durch Überprüfung der Rechnung aktualisieren",
    "edit_bill": "Rechnung bearbeiten",
    "reset": "Zurücksetzen",
    "reset_friends": "Alle splittings löschen?",
    "reset_friends_description": "Alle Aufteilungen werden gelöscht. Sie müssen die Elemente erneut aufteilen. Weiter?",
    "reset_friends_yes": "Ja, klar",
    "reset_all_changes_to_the_bill": "Alle Änderungen an der Rechnung zurücksetzen?",
    "reset_all_changes_to_the_bill_description": "Die Änderungen an den Artikeln werden nicht zurückgesetzt - nur die Rechnungsdaten werden geändert. Möchten Sie fortfahren?",
    "reset_changes_modal_yes": "Ja, Änderungen zurücksetzen",
    "reset_changes_modal_no": "Nein, abbrechen",
    "add_item_header": "Element hinzufügen",
    "add_item_description": "Neue Position zur Rechnung hinzufügen, wenn sie nicht vorhanden ist",
    "add_item_category_placeholder": "Wählen Sie die Kategorie",
    "edit_bill_view_bill_action": "Über das Bearbeiten",
    "edit_bill_expected_price": "(Erwarteter Preis: %{price})",
    "data_time": "Datum und Uhrzeit",
    "total_price": "Gesamtpreis",
    "price_conflict_warning_text": "Der Gesamtpreis der Rechnung weicht von den berechneten Preisen aller Artikel um %{price} ab (erwarteter Preis ist %{expectedPrice}). Bitte manuell ändern, wenn Sie die Rechnung korrekt aufteilen möchten",
    "delete_item_modal_header": "Diesen Artikel löschen?",
    "delete_bill_modal_header": "Dieses Gesetz streichen?",
    "delete_item_modal_description": "Bist du sicher, dass du diesen Artikel löschen möchtest?",
    "delete_bill_modal_description": "Sind Sie sicher, dass Sie diese Rechnung löschen wollen?",
    "yes_delete": "Ja, löschen",
    "no_go_back": "Nein, zurück",
    "dont_show_again": "Nicht mehr anzeigen",
    "skip_tutorial": "Tutorial überspringen",
    "back": "Zurück",
    "how_to_split_header": "Wie man die Rechnung teilt",
    "how_to_split_description": "Wählen Sie im Abschnitt „Rechnungspositionen“ die Artikel aus Ihrer Bestellung aus und fügen Sie sie zu Ihrer Rechnung hinzu.",
    "edit_errors_header": "Fehler bearbeiten",
    "edit_errors_description": "Bei falschen Informationen in der App können Sie den Artikel bearbeiten, indem Sie ihn lange drücken.",
    "add_reciepients_header": "Weitere Empfänger hinzufügen",
    "add_reciepients_description": "Nachdem Sie alle Artikel Ihrer Bestellung ausgewählt haben, fügen Sie den nächsten Empfänger hinzu und wiederholen Sie den Auswahlprozess!",
    "share_results_header": "Ergebnisse teilen",
    "share_results_description": "Wenn alle Artikel der Rechnung aufgeteilt sind, drücken Sie “Weiter” und teilen Sie die Ergebnisse mit Ihren Freunden!",
    "tutorial_message_text": "Während wir Ihre Rechnung erkennen, lernen wir, wie man die Rechnung teilt! 😉",
    "calculation_error_modal_header": "Berechnungsfehler",
    "calculation_error_description": `Es sind einige Fehler bei der Erkennung dieses Artikels aufgetreten 😥

Bitte überprüfen und ändern Sie den Preis oder die Menge dieses Artikels, bevor Sie ihn unter Freunden teilen können.`,
    "edit_item_calculation_error_label": "Berechnungsfehler: %{amount} × %{price} ≠ %{totalPrice}",
    "edit_item_calculation_error_label_with_discount": "Berechnungsfehler: %{amount} × %{price} - %{discount} ≠ %{totalPrice}",
    "recalculate": "Neu berechnen",
    "to_main_menu": "Zum Hauptmenü",
    "to_method_select": "Zur Methodenwahl",
    "select_all": "Alle auswählen",
    "receipts_manage_header": "Ihre Rechnungen",
    "today": "Heute",
    "yesterday": "Gestern",
    "no_receipts_found_title": "Keine gespeicherten Rechnungen",
    "no_receipts_found_description": "Sie haben noch keine Quittungen oder Rechnungen gespeichert. Nachdem Sie Ihre Aufteilung abgeschlossen haben, drücken Sie „Speichern“, um Ihre Rechnung hier hinzuzufügen",
    "view_statistics": "Statistiken ansehen",
    "receipts_manage_filter_modal_header": "Filter",
    "receipts_manage_filter_modal_action_clear": "Filter löschen",
    "receipts_manage_filter_modal_action_apply": "Filter anwenden",
    "receipts_manage_filter_modal_action_cancel": "Abbrechen",
    "receipts_manage_filter_modal_date_group": "Datum",
    "receipts_manage_filter_modal_date_range_placeholder": "Datumsbereich auswählen",
    "receipts_manage_filter_modal_date_sort_asc": "Aufsteigende Sortierung",
    "receipts_manage_filter_modal_date_sort_desc": "Absteigende Sortierung",
    "receipts_manage_filter_modal_date_picker_apply": "Übernehmen",
    "receipts_manage_filter_modal_date_picker_cancel": "Abbrechen",
    "receipts_manage_filter_modal_date_picker_reset": "Auf Standard zurücksetzen",
    "receipts_manage_filter_modal_price_group": "Preis",
    "receipts_manage_filter_modal_price_sort_asc": "Aufsteigend",
    "receipts_manage_filter_modal_price_sort_desc": "Absteigend",
    "receipts_manage_filter_modal_price_sort_default": "Standard",
    "receipts_manage_filter_modal_discard_description": "Änderungen, die jetzt vorgenommen wurden, gehen verloren. Möchten Sie fortfahren?",
    "friends_manage_filter_modal_header": "Freundeslisten-Filter",
    "friends_manage_filter_modal_action_clear": "Alle löschen",
    "friends_manage_filter_modal_action_apply": "Filter anwenden",
    "friends_manage_filter_modal_action_cancel": "Abbrechen",
    "friends_manage_filter_modal_all": "Alle",
    "friends_manage_filter_modal_favorite": "Favoriten",
    "friends_manage_filter_modal_non_favorite": "Nicht-Favoriten",
    "friends_manage_filter_modal_sort_name_field": "Nach Name sortieren",
    "friends_manage_filter_modal_sort_asc": "Aufsteigend",
    "friends_manage_filter_modal_sort_desc": "Absteigend",
    "friends_manage_filter_modal_status_field": "Status",
    "friends_manage_filter_modal_last_splitted_field": "Zuletzt getrennt",
    "no_found_primary_action": "Zurück zum Hauptmenü",
    "no_friends_found_title": "Keine Freunde gefunden",
    "no_friends_found_description": "Sie können Freunde manuell hinzufügen,\bindem Sie auf die Schaltfläche unten drücken.",
    "nothing_found_title": "Nichts gefunden",
    "nothing_found_description_splitters": `Es wurden keine Freunde für Ihre Anfrage gefunden,
bitte passen Sie Ihre Suchanfrage an.`,
    "nothing_found_description_receipts": `Es wurden keine Quittungen zu Ihrer Anfrage gefunden,
bitte passen Sie Ihre Suchanfrage an.`,
    "receipts_loading": "Rechnungen laden...",
    "receipt_view_back": "Zurück",
    "receipt_view_start_splitting": "Aufteilung starten",
    "network_request_failed_header": "Netzwerkanfrage fehlgeschlagen",
    "network_request_failed_description": "Dieses Foto konnte nicht geladen werden😔 Bitte versuchen Sie es erneut",
    "back_to_list": "Zurück zur Liste",
    "resplitting_loading_title": "Wir laden Daten für die Aufteilung",
    "resplitting_loading_description": "Bitte warten Sie, während wir die Daten für die Aufteilung laden",
    "receipt_saved": "Bill ist gerettet",
    "saved_successfully": "Die Rechnung ist erfolgreich gespeichert! 🎉",
    "receipt_not_saved": "Ups... Etwas ist schiefgelaufen",
    "saving_failed": "Die Rechnung konnte nicht gespeichert werden 😥 Bitte versuchen Sie es erneut oder überprüfen Sie Ihre Verbindung.",
    "image_not_found": "Bild nicht gefunden",
    "image_not_found_details": "Bitte gehen Sie zurück zum vorherigen Menü und wählen Sie das Bild erneut aus",
    "list_of_friends_header": `Freunde, mit denen
Sie die Rechnung teilen`,
    "all_friends": "Alle Freunde",
    "add_new_friend": "Einen neuen Freund hinzufügen",
    "unknown": "Unbekannt",
    "currency": "Währung",
    "select_currency": "Währung auswählen",
    "search": "Suche",
    "bug_report_modal_header": "Fehlerbericht",
    "bug_report_modal_description": "Bitte beschreiben Sie den aufgetretenen Fehler, das hilft uns, die Anwendung zu verbessern!",
    "bug_summary_field": "Fehlerkurzfassung",
    "bug_summary_field_placeholder": "Erklären Sie den Fehler in wenigen Worten",
    "bug_description_field": "Beschreibung",
    "bug_description_field_placeholder": "Beschreiben Sie detailliert, welchen Fehler Sie festgestellt haben",
    "send_report": "Bericht senden",
    "bug_attach_field": "Bildschirmfotos anhängen (optional)",
    "bug_attach_holder": "Zum Anhängen klicken",
    "bug_attach_holder_constraints": "Max. Dateien: %{count} Dateien bis zu %{size} MB",
    "add_recognition_results": "Erkennungsergebnisse hinzufügen",
    "file_size_exceeded": "Dateigröße überschreitet das Limit von %{size}. Bitte wählen Sie eine kleinere Datei.",
    "file_count_exceeded": "Sie können nicht mehr als %{count} Dateien hochladen!",
    "bug_report_sent": "Fehlerbericht gesendet",
    "bug_report_sent_successfully": "Fehlerbericht erfolgreich gesendet! 🎉",
    "bug_report_not_sent": "Hoppla... Etwas ist passiert",
    "bug_report_failed": "Fehlerbericht konnte nicht gesendet werden. 😥 Bitte versuchen Sie es erneut oder überprüfen Sie Ihre Verbindung.",
    "bug_summary_required": "Zusammenfassung muss ausgefüllt werden",
    "delete_bill": "Rechnung löschen",
    "share_results": "Ergebnisse teilen",
    "error_updating_friend_header": "Fehler beim Aktualisieren eines Freundes",
    "error_updating_friend_description": "Es ist ein unerwarteter Fehler aufgetreten. Bitte versuchen Sie es erneut",
    "favourite": "Favorit",
    "edit_friend": "Freund bearbeiten",
    "delete_friend": "Freund löschen",
    "splitting_history": "Aufteilung der Geschichte",
    "view_bill": "Rechnung ansehen",
    "friend_empty_history": "Sie haben noch keine Rechnungen \n" +
        "mit dieser Freund geteilt",
    "delete_friend_modal_header": "Diesen Freund löschen?",
    "delete_friend_modal_description": "Sind Sie sicher? Alle damit verbundenen Abspaltungen\nwerden ebenfalls gelöscht",
    "deletion_error": "Fehler bei der Löschung",
    "friend_deletion_error": "Beim Löschen dieses Freundes ist ein unerwarteter Fehler aufgetreten. Bitte versuche es erneut",
    "prev_friend_empty_state_header": "Keine Freunde gefunden",
    "prev_friend_empty_state_description": "Es scheint, als hättest du dich noch mit niemandem getrennt. Füge einen neuen Freund hinzu, indem du den Reiter „Neuer Freund“ oben benutzt.",
    "avatar": "Avatar",
    "select_avatar": "Avatar auswählen",
    "select": "Wählen Sie",
    "divide_item_description": "Geben Sie die Anzahl der Teile ein, in die diese Position neu unterteilt werden soll.\n" +
        "Ein Beispiel: Sie haben 2 Pizzen, 3 Freunde.\n" +
        "Geben Sie 6 Teile ein, und dann können Sie Positionen als separate zuweisen.",
    "divide_count": "Anzahl dividieren",
    "current_item_price": "Aktueller Artikelpreis",
    "redivided_price": "Preis für einen neu aufgeteilten Artikel",
    "can_not_divide_alert_header": "Sie können diesen Artikel nicht teilen",
    "can_not_divide_alert_description": "Bitte korrigieren Sie die Artikeldaten vor der Aufteilung",
    "burger_profile": "Profil",
    "burger_settings": "Einstellungen",
    "statistics": "Statistiken",
    "statistics_description": "Verfolgen Sie Ihre Ausgaben",
    "statistics_by_date": "Nach Datum",
    "statistics_by_date_description": "Ausgaben nach Datum",
    "statistics_by_items": "Nach Artikeln",
    "statistics_by_items_description": "Ausgaben nach Artikelkategorien",
    "statistics_by_business": "Nach Unternehmen",
    "statistics_by_business_description": "Ausgaben nach Kategorien von Unternehmen",
    "select_ranging": "Bereich auswählen",
    "this_week": "Diese Woche",
    "this_month": "Diesen Monat",
    "this_year": "Dieses Jahr",
    "custom_range": "Benutzerdefinierter Bereich",
    "total_spent": "Insgesamt ausgegeben:",
    "most_spent_on": "Meist ausgegeben für:",
    "burger_bug_report": "Einen Fehler melden",
    "select_language": "Sprache auswählen",
    "language": "Sprache",
    "language_english": "English",
    "language_german": "Deutsch",
    "profile_bills_splitted": "Rechnungen geteilt",
    "profile_bill_splitted": "Rechnung geteilt",
    "profile_friends": "Freunde",
    "profile_friend": "Freund",
    "edit_profile": "Profil bearbeiten",
    "error_updating_profile_header": "Fehler beim Aktualisieren des Profils",
    "error_updating_profile_description": "Es ist ein unerwarteter Fehler aufgetreten. Bitte versuchen Sie es erneut",
    "edit_profile_modal_title": "Profil bearbeiten",
    "profile_name_label": "Profilname",
    "profile_name_placeholder": "Ihr Name",
    "profile_name_validation": "Name ist erforderlich",
    "email_label": "E-mail",
    "email_placeholder": "z.B. john.doe@gmail.com",
    "finish_review": "Überprüfung abschließen",
    "cancel_reviewing_title": "Überprüfung abbrechen?",
    "cancel_reviewing_description": "Diese Rechnung ist noch nicht gespeichert. Sind Sie sicher, dass Sie die Speicherung abbrechen möchten?",
    "cancel_reviewing_continue_reviewing": "Durchsicht fortsetzen",
    "cannot_change_email": "Sie können Ihre E-Mail nicht ändern, weil Sie in einem sozialen Netzwerk angemeldet sind",
    "category_receipt_restaurant": "Restaurant",
    "category_receipt_shop": "Geschäft",
    "category_receipt_medical": "Medizinisch",
    "category_receipt_gas": "Tankstelle",
    "category_receipt_entertainment": "Unterhaltung",
    "category_receipt_car": "Auto",
    "category_receipt_utilities": "Versorgungsunternehmen",
    "category_receipt_transport": "Transport",
    "category_receipt_services": "Dienstleistungen",
    "category_receipt_sport": "Sport",
    "category_receipt_other": "Sonstiges",
    "category_item_food": "Essen",
    "category_item_drinks": "Getränke",
    "category_item_hygiene": "Hygiene",
    "category_item_home": "Zuhause",
    "category_item_electronics": "Elektronik",
    "category_item_clothing": "Kleidung",
    "category_item_entertainment": "Unterhaltung",
    "category_item_sports": "Sport",
    "category_item_car": "Auto",
    "category_item_kids": "Kinder",
    "category_item_stationery": "Schreibwaren",
    "category_item_pets": "Haustiere",
    "category_item_travel": "Reisen",
    "category_item_utilities": "Versorgungsunternehmen",
    "category_item_services": "Dienstleistungen",
    "category_item_medicine": "Medizin",
    "category_item_transportation": "Transport",
    "category_item_education": "Bildung",
    "category_item_tips": "Tipps",
    "category_item_discount": "Rabatte",
    "category_item_adjustments": "Anpassungen",
    "category_item_other": "Sonstiges",
    "select_category": "Kategorie auswählen",
    "item_category": "Gegenstandskategorie",
    "category": "Kategorie",
    "duplicates_title": "Ihre Rechnung wurde bereits vorher gespeichert",
    "duplicates_description_singular": "Wir haben festgestellt, dass Sie diese Rechnung bereits gespeichert haben. Bitte überprüfen Sie den Screenshot Ihrer vorherigen Rechnung und ersetzen Sie sie oder speichern Sie sie als neue Rechnung.",
    "duplicates_description_plural": "Wir haben festgestellt, dass Sie diese Rechnung bereits gespeichert haben. Bitte sehen Sie sich die Screenshots Ihrer früheren Rechnungen an und wählen Sie eine davon aus, um sie zu ersetzen oder als neue Rechnung zu speichern.",
    "duplicates_override_singular": "Dieses Gesetz aufheben",
    "duplicates_override_plural": "Ausgewählte Rechnung außer Kraft setzen",
    "duplicates_continue": "Fortsetzen als weitere Rechnung",
    "export_modal_header": "Belege als CSV exportieren",
    "export_range": "Exportbereich",
    "all_time": "Gesamte Zeit",
    "grouping_type": "Gruppierungstyp",
    "export_receipt_categories_grouping": "Nach Belegkategorien",
    "export_item_categories_grouping": "Nach Artikelkategorien",
    "export_default_grouping": "Standardmäßig",
    "export": "Exportieren",
    "download_csv_file": "CSV-Datei herunterladen",
    "select_grouping": "Gruppierung auswählen",
    "export_success_modal_header": "CSV-Datei erfolgreich erstellt",
    "export_success_modal_description": "Drücke die Schaltfläche unten, um die Datei auf dein Gerät herunterzuladen. Du kannst die Datei auch in sozialen Netzwerken teilen.",
    "failed_to_create_export_file": "Fehler beim Erstellen der Exportdatei.\nVersuche es später erneut.",
    "success": "Erfolg",
    "export_file_saved": "Die Datei wird im Ordner Downloads/Billka unter dem Namen",
    "error": "Fehler",
    "permission_denied": "Zugriff verweigert",
    "failed_to_download_file": "Fehler beim Herunterladen der Datei",
    "sharing_not_available": "Teilen nicht verfügbar",
    "failed_to_share_file": "Fehler beim Teilen der Datei",
    "failed_to_open_folder": "Ordner konnte nicht geöffnet werden",
    "check_version_update_btn": "Aktualisieren",
    "check_version_fail_title": "Ihre Version ist veraltet",
    "check_version_fail_description": "Bitte laden Sie die neuesten Updates herunter, um die App zu verwenden",
};

export default de;
