const en = {
    "welcome_to": "Welcome to 👋",
    "app_name": "Reader AI",
    "please_login": "Please login to continue",
    "enter_credentials": "Enter your credentials",
    "login_email": "E-mail",
    "login_password": "Password",
    "validation_error_password": "Password must be at least 6 characters long",
    "login_via_email": "Login via e-mail",
    "login_with_google": "Login with Google",
    "or": "or",
    "login": "Login",
    "sign_up": "Sign up",
    "forgot_password": "Forgot Password?",
    "reset_password": "Reset Password",
    "forgot_password_instructions": "Enter your email address and we'll send you a code to reset your password.",
    "send_reset_code": "Send Reset Code",
    "verify_code": "Verify Code",
    "verify_code_instructions": "Enter the 6-digit code we sent to your email address.",
    "verification_code": "6-digit code",
    "new_password": "New Password",
    "new_password_instructions": "Create a new password for your account.",
    "confirm_password": "Confirm Password",
    "passwords_dont_match": "Passwords don't match",
    "update_password": "Update Password",
    "signup_success": "Check your email for a confirmation link to activate your account",
    "request_reset_success_title": "Password Reset Email Sent",
    "request_reset_success_description": "Check your email for a 6-digit code to reset your password",
    "new_password_success_title": "Password Updated",
    "new_password_success_description": "Your password has been successfully updated. You can now log in with your new password",
    "error_login_title": "Login Error",
    "error_login_via_google": "Failed to retrieve profile after Google sign in",
    "error_login_validation": "Please enter email and password",
    "error_login_validation_email": "Please enter a valid email address, e.g. johndoe@example.com",
    "error_login_validation_password": "Password must be at least 6 characters long",
    "error_login_banned": "Please, confirm deletion request or cancel it for further login",
    "error_login_invalid_credentials": "Email or password is wrong",
    "error_login_email_not_confirmed": "Email is not confirmed. Please check your inbox and confirm your email address",
    "error_signup_title": "Sign Up Error",
    "error_google_title": "Google Login Error",
    "error_reset_pass_title": "Password Reset Error",
    "error_reset_pass_code_invalid_description": "Please enter the 6-digit code from your email",
    "error_reset_code_verification_title": "Code Verification Error",
    "error_reset_code_verification_description": "Verification failed. Please try again.",
    "error_reset_pass_new_pass_not_present": "Please enter a new password",
    "error_reset_pass_new_pass_invalid": "Password must be at least 6 characters long",
    "error_reset_pass_new_pass_unmatch": "Passwords do not match",
    "verify_email": "Verify Email",
    "verify_email_instructions": "Please enter the verification code sent to your email address.",
    "email_verification_required": "Email Verification Required",
    "email_verification_explanation": "Your email address needs to be verified before you can log in. Would you like to verify now?",
    "verify_now": "Verify Now",
    "later": "Later",
    "email_verification_required_after_signup": "Please verify your email address to activate your account. We've sent a verification code to your email.",
    "verification_code_sent_title": "Verification Code Sent",
    "verification_code_sent_description": "We've sent a verification code to your email. Please check your inbox and enter the code below.",
    "error_verification_title": "Verification Error",
    "error_verification_code_invalid": "Please enter a valid verification code.",
    "error_verification_unknown": "An unknown error occurred during verification. Please try again.",
    "email_verification_success_title": "Email Verified",
    "email_verification_success_description": "Your email has been successfully verified.",
    "resend_code": "Resend Code",
    "email_verification_description": "Enter code or open the link sent to your email.",
    "logout": "Logout",
    "books": "Books",
    "children": "Children",
    "error": "Error",
    "failed_to_fetch_books": "Failed to fetch books",
    "please_try_again_later": "Please, try again later",
    "back": "Back",
    "add_book": "Add book",
    "cancel": "Cancel",
    "save": "Save",
    "name": "Name",
    "name_validation": "Please enter book's name",
    "author": "Author",
    "author_validation": "Please enter book's author",
    "select_book": "Select book",
    "file_name": "File name",
    "select": "Select",
    "discard_changes_modal_header": "Discard changes?",
    "discard_book_adding_modal_description": "All changes made to the book will not be saved, do you want to continue?",
    "no": "No",
    "yes": "Yes",
    "failed_to_fetch_children": "Failed to fetch children",
    "select_child": "Select child",
    "switch_to_child_mode": "Switch to child mode",
    "switch_to_parent_mode": "Switch to parent mode",
    "child_name": "Child name",
    "add_child": "Add child",
    "failed_to_save_child": "Failed to add child",
    "list_of_accesses": "List of accesses",
    "failed_to_grant_access": "Failed to grant access",
    "grant_access": "Grant access",
    "read": "Read",
    "failed_to_fetch_child": "Failed to fetch child",
    "tests": "Tests",
    "failed_to_fetch_tests": "Failed to fetch tests",
    "failed_to_fetch_test": "Failed to fetch test",
    "pages_range": "Pages %{start} - %{end}",
    "questions_amount": "Questions amount",
    "test_status": "Status:",
    "COMPLETED": "Completed",
    "NOT_STARTED": "Not started",
    "IN_PROGRESS": "In Progress",
    "failed_to_create_test": "Failed to create test",
    "create_test": "Create test",
    "create_test_modal_description": "Create test for book %{bookName} for %{childName}",
    "assign_test": "Assign test",
    "start_page": "Start page",
    "end_page": "End page",
    "start_page_validation": "Start page must be greater than 0 and lower than end page",
    "end_page_validation": "End page must be greater than 0 and greater than start page",
    "questions_amount_validation": "Amount must be greater than 0",
    "test_exists_message_text": "There is test after page %{page}",
    "go_to_test": "Go to test",
    "correct_answer_amount": "Correct answers amount: %{amount}",
    "result_grade": "Grade: %{grade}",
    "back_to_home": "Back to home",
    "test_button_child_name": "Child: %{childName}",
    "test_button_questions_amount": "Questions: %{questionsAmount}",
    "book": "Book",
    "create_test_for_child": "Create test for %{childName}",
    "avg_grade": "Average grade",
    "reading_statistics": "Reading statistics",
    "statistics": "Statistics",
    "completed": "Completed",
    "reading_time": "Reading time",
    "pages": "Pages",
    "failed_to_fetch_progress": "Failed to fetch progress",
};

export default en;
