const en = {
    "welcome_to": "Welcome to 👋",
    "app_name": "Billka AI",
    "app_description": "Receipts split & analysis",
    "please_login": "Please login to continue",
    "enter_credentials": "Enter your credentials",
    "login_email": "E-mail",
    "login_password": "Password",
    "validation_error_password": "Password must be at least 6 characters long",
    "login_via_email": "Login via e-mail",
    "login_with_google": "Login with Google",
    "or": "or",
    "login": "Login",
    "sign_up": "Sign up",
    "forgot_password": "Forgot Password?",
    "reset_password": "Reset Password",
    "forgot_password_instructions": "Enter your email address and we'll send you a code to reset your password.",
    "send_reset_code": "Send Reset Code",
    "verify_code": "Verify Code",
    "verify_code_instructions": "Enter the 6-digit code we sent to your email address.",
    "verification_code": "6-digit code",
    "new_password": "New Password",
    "new_password_instructions": "Create a new password for your account.",
    "confirm_password": "Confirm Password",
    "passwords_dont_match": "Passwords don't match",
    "update_password": "Update Password",
    "logout": "Logout",
    "welcome": "Welcome!",
    "hello": "Hello!🌙",
    "good_morning": "Good morning!☀️",
    "good_afternoon": "Good afternoon!👋",
    "good_evening": "Good evening!🌃",
    "greeting": "Hope you are having a\u00A0wonderful\u00A0day!",
    "upload_bill_modal_header": "Upload bill",
    "upload_bill_modal_description": "Choose a photo from your gallery or take a new one",
    "upload_bill_modal_take_photo": "📸 Take a photo",
    "upload_bill_modal_gallery": "🖼️ Choose from gallery",
    "upload_bill": "Upload bill",
    "recognize_fast": "⚡️ Fast",
    "recognize_quality": "🔥 High-quality",
    "manage_receipts": "Manage bills",
    "list_of_friends": "List of friends",
    "cancel": "Cancel",
    "recognizing_in_progress_title": "Take a little break...",
    "recognizing_in_progress_msg": "We will recognize the items on your bill.\nIt won't take long",
    "error_header": "Oops! Something went wrong",
    "error_large_photo_header": "The image is too large",
    "error_large_photo_msg": "Please take a new photo or upload a file less than 10 MB in size",
    "error_retake_photo_msg": "We couldn't recognize bill in your photo 😥\nPlease retake the photo",
    "error_retry_fetch_msg": "Sorry, some loading error happened 😥\nPlease retry",
    "error_go_home_action": "Go home",
    "error_retake_photo_action_camera": "Retake photo",
    "error_retake_photo_action_gallery": "Select from gallery",
    "error_retry_action": "Retry",
    "error_creating_friend_header": "Error while creating a friend",
    "error_creating_friend_description": "Some unexpected error happened. Please try again",
    "try_again": "Try again",
    "gallery": "Gallery",
    "take-photo": "Take a photo",
    "flash": "Flash",
    "permission-denied": "Please provide permission to camera",
    "grant-permission": "Grant permission",
    "camera_permission_error": "Error",
    "camera_permission_error_description": "Camera permission is required to take a photo",
    "bill_ready_to_split_header": "Only one step\nis left...",
    "bill_ready_to_split_body": "We need to recognize items in your bill.\nPlease choose the way below:",
    "view_receipt_details": "View receipt details",
    "choosing_flow_header": "Your bill is recognized!",
    "choosing_flow_description": `Do you wish to split it between your friends or
just view results?`,
    "view_without_splitting": "View without splitting",
    "split_the_bill": "Split the bill",
    "splitting_view_next_button": "View splitting results",
    "next": "Next",
    "discount": "discount",
    "tip": "tip",
    "edit_bill_action": "Edit bill",
    "bill_items": "Bill items",
    "no_items_splitting_title": "No items left",
    "no_items_splitting_description": "Your bill has no items.\nPress \"+\" button to add item manually.",
    "unselected_items": "Unselected bill items",
    "itemDescription": "%{quantity}%{optionalOfQuantity} × %{itemPrice}",
    "optionalOfQuantity": " (of %{itemQuantity})",
    "cancel_changes": "Cancel changes",
    "splitting_not_saving": "Splitting progress will not be saved",
    "yes": "Yes",
    "no": "No",
    "add_friend_tab_new_friend": "New friend",
    "add_friend_tab_all_friends": "All friends",
    "enter_name": "Enter name",
    "add_friend_input_name_placeholder": "Input name here",
    "add_email": "Add e-mail (optional)",
    "add_favorite": "Save as favorite",
    "add_friend_input_email_placeholder": "e.g. john.doe@gmail.com",
    "add_friend_btn": "Confirm %{splitterName}",
    "add_friends_modal_title": "Add friends",
    "add_friend_modal_title": "Add friend",
    "add_friends_modal_new_splitter_description": "A friend is saved only when the bill is.",
    "name": "Name",
    "email": "E-mail (optional)",
    "update_friend_modal_title": "Update friend",
    "edit_name": "The name must not be empty and must be unique",
    "edit_email_validation": "e-mail must be in the format user@example.com, with one '@' and a valid domain",
    "friend_name_invalid": "Friend with this name already exists",
    "friend_email_invalid": "Enter valid e-mail",
    "previous_friends_favorite_group": "Favorite",
    "previous_friends_nonfavorite_group": "Others",
    "add_friend_discard_changes_title": "Discard changes?",
    "add_friend_discard_changes_description": "All changes will be lost. Do you want to continue?",
    "add_friend_discard_changes_no": "No, stay",
    "add_friend_discard_changes_yes": "Yes, discard changes",
    "change_friend_modal_title": "Change friend",
    "change_friend_btn": "Change friend",
    "delete_friend_btn": "Delete friend",
    "delete_friend_header": "Are you sure you want to delete this friend?",
    "delete_friend_description": "This person's items will be unassigned too. Delete this friend?",
    "me": "Me",
    "my": "my",
    "item": "item",
    "items": "items",
    "add_to_bill": "Add %{quantity} %{itemWord} to bill of %{splitterName} (%{price})",
    "add_to_my_bill": "Add %{quantity} %{itemWord} to my bill (%{price})",
    "cancel_splitting_question": "Cancel splitting?",
    "cancel_splitting": "Cancel splitting",
    "continue_splitting": "Continue splitting",
    "finish": "Finish",
    "finish_splitting": "Finish splitting",
    "finish_splitting_title": "Splitting result",
    "finish_splitting_no_items_title": "No items were split",
    "finish_splitting_no_items_description": "To view splitting results assign items from your bill to one or more friend, on splitting screen.",
    "finish_splitting_back": "Back to splitting",
    "finish_splitting_modal_title": "Save result?",
    "finish_splitting_modal_save_with_splitting": "Save with splitting",
    "finish_splitting_modal_save_without_splitting": "Save without splitting",
    "finish_splitting_modal_dont_save": "Don't save",
    "friend_no_name": "Your items %{emoji}",
    "friend_with_name": "Items for %{name} %{emoji}",
    "share_button": "Share",
    "share_message_title": "Hi! Here is your share of the bill from %{storeName} on %{date}.",
    "share_all_message_title": "Hi! Here is share of the bill from %{storeName} on %{date}.",
    "share_message_title_no_date": "Hi! Here is your share of the bill from %{storeName}.",
    "share_all_message_title_no_date": "Hi! Here is share of the bill from %{storeName}.",
    "share_message_person": "== %{name} %{emoji} - %{totalPrice} ==\n%{items}",
    "share_message_splitting": "%{name} - %{totalPrice}",
    "share_message_total": "Your total amount is %{totalPrice} 🤗",
    "share_all_message_total": "Total amount is %{totalPrice} 🤗",
    "your_items": "Your items %{emoji}",
    "splitting_header": "Items of %{splitterName} %{emoji}",
    "ok": "OK",
    "can_not_change_friend": "You can not change friend",
    "confirm_before_change_friend": "Confirm items before switching friend",
    "divide_item": "Divide item",
    "edit_item": "Edit item",
    "delete_item": "Delete item",
    "edit_item_modal_header": "Edit item",
    "edit_item_modal_description": "Edit information if the data in the bill does not match the data in the app",
    "edit_item_modal_save": "Save",
    "edit_item_modal_cancel": "Cancel",
    "edit_item_name_field": "Item name",
    "edit_item_name_field_placeholder": "Enter item name",
    "edit_item_name_validation": "Please enter item’s name",
    "edit_item_price_field": "Price",
    "edit_item_price_validation": "Price should be digital",
    "edit_item_currency_validation": "Not valid currency code",
    "edit_item_discount_field": "Discount",
    "edit_item_discount_validation": "Discount must be 0 or greater",
    "edit_item_quantity_field": "Amount",
    "edit_item_quantity_validation_zero": "Amount should be greater than 0",
    "edit_item_quantity_validation_splitted": "Amount should be greater than the amount that is already splitted",
    "edit_item_total_price_field": "Total price (autocalculated)",
    "edit_item_total_price_with_discount": "Total price with %",
    "edit_item_view_bill_action": "View bill",
    "edit_item_about_editing_action": "About splits editing",
    "edit_item_about_editing_modal_description": `
Since you've already splitted this item, now you're changing original item, not selected splitting.
                            
If you change price, we will recalculate your splittings. Unfortunately, you can reduce amount only by value that is remaining for this item.
                            
To reduce it even more, you should remove splittings.`.trim(),
    "edit_item_about_editing_modal_ok": "Got it",
    "edit_bill_name_field": "Bill name",
    "edit_bill_name_field_placeholder": "Enter bill or store name",
    "edit_bill_name_validation": "Please enter bill or store name",
    "reset_all_changes_to_the_item": "Reset all changes to the item %{name}",
    "reset_all_changes_to_the_item_description": "%{name} will be replaced with original one. Do you want to continue?",
    "discard_changes_modal_header": "Discard changes?",
    "discard_item_changes_modal_description": "All changes made to the item will not be saved, do you want to continue?",
    "discard_receipt_changes_modal_description": "All changes made to the bill will not be saved, do you want to continue?",
    "discard_bug_report_modal_description": "All prepared data for the bug report will be lost, do you want to continue?",
    "discard_changes_modal_no": "No, stay",
    "discard_changes_modal_yes": "Yes, discard changes",
    "save": "Save",
    "edit_bill_general_info": "General info of the scanned bill. If some information isn’t right, please update the parameters by checking the bill",
    "edit_bill": "Edit Bill",
    "reset": "Reset",
    "reset_friends": "Clear all splittings?",
    "reset_friends_description": "All splittings are going to be deleted. You will have to split items again. Continue?",
    "reset_friends_yes": "Yes, clear",
    "reset_all_changes_to_the_bill": "Reset all changes to the bill?",
    "reset_all_changes_to_the_bill_description": "Item changes won’t be resetted — only bill info will be changed. Do you want to continue?",
    "reset_changes_modal_yes": "Yes, reset changes",
    "reset_changes_modal_no": "No, cancel",
    "add_item_header": "Add item",
    "add_item_description": "Add new item to the bill, if it isn't present",
    "add_item_category_placeholder": "Choose the category",
    "edit_bill_view_bill_action": "View bill",
    "edit_bill_expected_price": "(Expected price: %{price})",
    "data_time": "Date & time",
    "total_price": "Total price",
    "price_conflict_warning_text": "The total price of the bill differs from the calculated prices of all items by %{price} (expected price is %{expectedPrice}). Please change manually if you want to correctly split the bill",
    "delete_item_modal_header": "Delete this item?",
    "delete_bill_modal_header": "Delete this bill?",
    "delete_item_modal_description": "You sure you want to delete this item?",
    "delete_bill_modal_description": "You sure you want to delete this bill?",
    "yes_delete": "Yes, delete",
    "no_go_back": "No, go back",
    "dont_show_again": "Don’t show this again",
    "skip_tutorial": "Skip tutorial",
    "back": "Back",
    "how_to_split_header": "How to split the bill",
    "how_to_split_description": "In the section “Bill Items” select items from your order and add them to your bill.",
    "edit_errors_header": "Edit errors",
    "edit_errors_description": "In case of incorrect info in the app you can edit item by holding tap on it.",
    "add_reciepients_header": "Add other reciepients",
    "add_reciepients_description": "After selecting all of your order items add next recipient and repeat selection process!",
    "share_results_header": "Share results",
    "share_results_description": "When all items from the bill are split - press “Next” and share results with your friends!",
    "tutorial_message_text": "While we are recognizing your bill, let's learn how to split the bill! 😉",
    "calculation_error_modal_header": "Calculation error",
    "calculation_error_description": `There are some mistakes happened while recognizing this item 😥
    
Please, review and change price or quantity of this item before you can split it among friends.`,
    "edit_item_calculation_error_label": "Calculation error: %{amount} × %{price} ≠ %{totalPrice}",
    "edit_item_calculation_error_label_with_discount": "Calculation error: %{amount} × %{price} - %{discount} ≠ %{totalPrice}",
    "recalculate": "Recalculate",
    "to_main_menu": "To main menu",
    "to_method_select": "To method select",
    "select_all": "Select all",
    "receipts_manage_header": "Your bills",
    "today": "Today, %{date}",
    "yesterday": "Yesterday, %{date}",
    "no_receipts_found_title": "No saved bills",
    "no_receipts_found_description": "You didn’t save any receipts or bills yet. After you finish your splitting press “Save” to add your bill here",
    "view_statistics": "View statistics",
    "receipts_manage_filter_modal_header": "Filter",
    "receipts_manage_filter_modal_action_clear": "Clear all",
    "receipts_manage_filter_modal_action_apply": "Apply filters",
    "receipts_manage_filter_modal_action_cancel": "Cancel",
    "receipts_manage_filter_modal_date_group": "Date",
    "receipts_manage_filter_modal_date_range_placeholder": "Select date range",
    "receipts_manage_filter_modal_date_sort_asc": "Ascending sort",
    "receipts_manage_filter_modal_date_sort_desc": "Descending sort",
    "receipts_manage_filter_modal_date_picker_apply": "Apply",
    "receipts_manage_filter_modal_date_picker_cancel": "Cancel",
    "receipts_manage_filter_modal_date_picker_reset": "Reset to default",
    "receipts_manage_filter_modal_price_group": "Price",
    "receipts_manage_filter_modal_price_sort_asc": "Ascending",
    "receipts_manage_filter_modal_price_sort_desc": "Descending",
    "receipts_manage_filter_modal_price_sort_default": "Default",
    "receipts_manage_filter_modal_discard_description": "Changes made right now will be lost. Do you want to continue?",
    "friends_manage_filter_modal_header": "Friends list filter",
    "friends_manage_filter_modal_action_clear": "Clear all",
    "friends_manage_filter_modal_action_apply": "Apply filters",
    "friends_manage_filter_modal_action_cancel": "Cancel",
    "friends_manage_filter_modal_all": "All",
    "friends_manage_filter_modal_favorite": "Favorite",
    "friends_manage_filter_modal_non_favorite": "Non-favorite",
    "friends_manage_filter_modal_sort_name_field": "Sort by name",
    "friends_manage_filter_modal_sort_asc": "Ascending",
    "friends_manage_filter_modal_sort_desc": "Descending",
    "friends_manage_filter_modal_status_field": "Status",
    "friends_manage_filter_modal_last_splitted_field": "Last splitted",
    "no_friends_found_title": "No friends found",
    "no_friends_found_description": "You can manually add friends by\npressing button below.",
    "no_found_primary_action": "Back to main menu",
    "nothing_found_title": "Nothing found",
    "nothing_found_description_splitters": `No friends were found with your request,
please adjust your search prompt.`,
    "nothing_found_description_receipts": `No receipts were found with your request,
please adjust your search prompt.`,
    "receipts_loading": "Loading bills...",
    "receipt_view_back": "Back",
    "receipt_view_start_splitting": "Start splitting",
    "network_request_failed_header": "Network request failed",
    "network_request_failed_description": "We couldn’t load this photo😔 Please try again",
    "back_to_list": "Back to list",
    "resplitting_loading_title": "We are loading data for splitting",
    "resplitting_loading_description": "Please wait a moment",
    "receipt_saved": "Bill is saved",
    "saved_successfully": "The bill is saved successfully! 🎉",
    "receipt_not_saved": "Oops... Something happened",
    "saving_failed": "Failed to save the bill 😥 Please try again or check your connection.",
    "image_not_found": "Image not found",
    "image_not_found_details": "Please go back to the previous menu and try selecting the image again",
    "list_of_friends_header": `Friends you
split the bill with`,
    "all_friends": "All friends",
    "add_new_friend": "Add a new friend",
    "unknown": "Unknown",
    "currency": "Currency",
    "select_currency": "Select currency",
    "search": "Search",
    "bug_report_modal_header": "Bug report",
    "bug_report_modal_description": "Please describe bug you encountered, it helps us build a better application!",
    "bug_summary_field": "Bug summary",
    "bug_summary_field_placeholder": "Explain bug in a few words",
    "bug_description_field": "Description",
    "bug_description_field_placeholder": "Describe in more detail, what bug you encountered",
    "send_report": "Send report",
    "bug_attach_field": "Attach screenshots (optional)",
    "bug_attach_holder": "Click to attach",
    "bug_attach_holder_constraints": "(Max. files: %{count} files up to %{size} MB)",
    "add_recognition_results": "Add recognition results",
    "file_size_exceeded": "File size exceeds the limit of %{size}. Please choose a smaller file.",
    "file_count_exceeded": "You can't upload more than %{count} files!",
    "bug_report_sent": "Bug report sent",
    "bug_report_sent_successfully": "Bug report sent successfully! 🎉",
    "bug_report_not_sent": "Oops... Something happened",
    "bug_report_failed": "Failed to send the bug report. 😥 Please try again or check your connection.",
    "bug_summary_required": "Summary must be filled in",
    "delete_bill": "Delete bill",
    "share_results": "Share results",
    "error_updating_friend_header": "Error while updating friend",
    "error_updating_friend_description": "Some unexpected error happened. Please try again",
    "favourite": "Favourite",
    "edit_friend": "Edit friend",
    "delete_friend": "Delete friend",
    "splitting_history": "Splitting history",
    "view_bill": "View bill",
    "friend_empty_history": "You didn’t split any bills \n" +
        "with this friend yet",
    "delete_friend_modal_header": "Delete this friend?",
    "delete_friend_modal_description": "Are you sure? All related splittings\nwill be deleted too",
    "deletion_error": "Deletion error",
    "friend_deletion_error": "Some unexpected error happened while deleting this friend. Please try again",
    "prev_friend_empty_state_header": "No friends found",
    "prev_friend_empty_state_description": "Seems like you didn’t split with anybody yet. Add a new friend by using “new friend” tab above.",
    "avatar": "Avatar",
    "select_avatar": "Select avatar",
    "select": "Select",
    "divide_item_description": "Enter the number of parts into which you want this position to be re-divided.\n" +
        "For example, you have 2 pizzas, 3 friends.\n" +
        "Enter 6 parts, and then you can assign items as separate ones.",
    "divide_count": "Divide count",
    "current_item_price": "Current item price",
    "redivided_price": "Price of one re-divided item",
    "can_not_divide_alert_header": "You can not divide this item",
    "can_not_divide_alert_description": "Please, correct item's data before dividing",
    "burger_profile": "Profile",
    "burger_settings": "Settings",
    "statistics": "Statistics",
    "statistics_description": "Track your spending",
    "statistics_by_date": "By date",
    "statistics_by_date_description": "Spending by date",
    "statistics_by_items": "By Items",
    "statistics_by_items_description": "Spending by category of items",
    "statistics_by_business": "By Business",
    "statistics_by_business_description": "Spending by category of business",
    "select_ranging": "Select ranging",
    "this_week": "This week",
    "this_month": "This month",
    "this_year": "This year",
    "custom_range": "Custom range",
    "total_spent": "Total spent:",
    "most_spent_on": "Most spent on:",
    "burger_bug_report": "Report a bug",
    "select_language": "Select Language",
    "language": "Language",
    "language_english": "English",
    "language_german": "Deutsch",
    "profile_bills_splitted": "Bills splitted",
    "profile_bill_splitted": "Bill splitted",
    "profile_friends": "Friends",
    "profile_friend": "Friend",
    "edit_profile": "Edit profile",
    "error_updating_profile_header": "Error while updating profile",
    "error_updating_profile_description": "Some unexpected error happened. Please try again",
    "edit_profile_modal_title": "Edit profile",
    "profile_name_label": "Profile name",
    "profile_name_placeholder": "Your name",
    "profile_name_validation": "Name is required",
    "email_label": "E-mail",
    "email_placeholder": "e.g. john.doe@gmail.com",
    "finish_review": "Finish the review",
    "cancel_reviewing_title": "Cancel reviewing?",
    "cancel_reviewing_description": "This bill is not saved yet. Are you sure you want to cancel saving?",
    "cancel_reviewing_continue_reviewing": "Continue reviewing",
    "cannot_change_email": "You can't change your E-mail because you are signed in with a social network",
    "category_receipt_restaurant": "Restaurant",
    "category_receipt_shop": "Shop",
    "category_receipt_medical": "Medical",
    "category_receipt_gas": "Gas",
    "category_receipt_entertainment": "Entertainment",
    "category_receipt_car": "Car",
    "category_receipt_utilities": "Utilities",
    "category_receipt_transport": "Transport",
    "category_receipt_services": "Services",
    "category_receipt_sport": "Sport",
    "category_receipt_other": "Other",
    "category_item_food": "Food",
    "category_item_drinks": "Drinks",
    "category_item_hygiene": "Hygiene",
    "category_item_home": "Home",
    "category_item_electronics": "Electronics",
    "category_item_clothing": "Clothing",
    "category_item_entertainment": "Entertainment",
    "category_item_sports": "Sports",
    "category_item_car": "Car",
    "category_item_kids": "Kids",
    "category_item_stationery": "Stationery",
    "category_item_pets": "Pets",
    "category_item_travel": "Travel",
    "category_item_utilities": "Utilities",
    "category_item_services": "Services",
    "category_item_medicine": "Medicine",
    "category_item_transportation": "Transportation",
    "category_item_education": "Education",
    "category_item_tips": "Tips",
    "category_item_discount": "Discount",
    "category_item_adjustments": "Adjustments",
    "category_item_other": "Other",
    "select_category": "Select category",
    "item_category": "Item category",
    "category": "Category",
    "duplicates_title": "Your bill was already saved before",
    "duplicates_description_singular": "We found that you have already saved this bill, please review the screenshot of your previous bill and replace it or save as a new one.",
    "duplicates_description_plural": "We found that you have already saved this bill, please review the screenshots of your previous bills and choose one of them to replace or save as a new one.",
    "duplicates_override_singular": "Override this bill",
    "duplicates_override_plural": "Override selected bill",
    "duplicates_continue": "Continue as another bill",
    "export_modal_header": "Export receipts to CSV",
    "export_range": "Export range",
    "all_time": "All time",
    "grouping_type": "Grouping type",
    "export_receipt_categories_grouping": "By receipt categories",
    "export_item_categories_grouping": "By item categories",
    "export_default_grouping": "By default",
    "export": "Export",
    "download_csv_file": "Download CSV file",
    "select_grouping": "Select grouping",
    "export_success_modal_header": "CSV file generated successfully",
    "export_success_modal_description": "Press button below to download file to your device. You can also share this file to socials.",
    "failed_to_create_export_file": "Failed to create export file.\nTry again later.",
    "success": "Success",
    "export_file_saved": "File is saved to Downloads/Billka folder with name %{fileName}",
    "error": "Error",
    "permission_denied": "Permission denied",
    "failed_to_download_file": "Failed to download file",
    "sharing_not_available": "Sharing not available",
    "failed_to_share_file": "Failed to share file",
    "failed_to_open_folder": "Failed to open folder",
    "open_in_files": "Open in files",
    "check_version_update_btn": "Update",
    "check_version_fail_title": "Your version is outdated",
    "check_version_fail_description": "Please download latest updates to use the app",
};

export default en;
