const en = {
    "books": "Books",
    "children": "Children",
    "error": "Error",
    "failed_to_fetch_books": "Failed to fetch books",
    "please_try_again_later": "Please, try again later",
    "back": "Back",
    "add_book": "Add book",
    "cancel": "Cancel",
    "save": "Save",
    "name": "Name",
    "name_validation": "Please enter book's name",
    "author": "Author",
    "author_validation": "Please enter book's author",
    "select_book": "Select book",
    "file_name": "File name",
    "select": "Select",
    "discard_changes_modal_header": "Discard changes?",
    "discard_book_adding_modal_description": "All changes made to the book will not be saved, do you want to continue?",
    "no": "No",
    "yes": "Yes",
    "failed_to_fetch_children": "Failed to fetch children",
    "select_child": "Select child",
    "switch_to_child_mode": "Switch to child mode",
    "switch_to_parent_mode": "Switch to parent mode",
    "child_name": "Child name",
    "add_child": "Add child",
    "failed_to_save_child": "Failed to add child",
    "logout": "Logout",
    "list_of_accesses": "List of accesses",
    "failed_to_grant_access": "Failed to grant access",
    "grant_access": "Grant access",
    "read": "Read",
    "failed_to_fetch_child": "Failed to fetch child",
    "tests": "Tests",
    "failed_to_fetch_tests": "Failed to fetch tests",
    "failed_to_fetch_test": "Failed to fetch test",
    "pages_range": "Pages %{start} - %{end}",
    "questions_amount": "Questions amount",
    "test_status": "Status: %{status}",
    "failed_to_create_test": "Failed to create test",
    "create_test": "Create test",
    "create_test_modal_description": "Create test for book %{bookName}",
    "assign_test": "Assign test",
    "start_page": "Start page",
    "end_page": "End page",
    "start_page_validation": "Start page must be greater than 0 and lower than end page",
    "end_page_validation": "End page must be greater than 0 and greater than start page",
    "questions_amount_validation": "Amount must be greater than 0",
    "test_exists_message_text": "There is test after page %{page}",
    "go_to_test": "Go to test",
    "correct_answer_amount": "Correct answers amount: %{amount}",
    "result_grade": "Grade: %{grade}",
    "back_to_home": "Back to home",
};

export default en;
